# github action for deploying to vercel from github

name: Deploy MAIN branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: 'Create env file'
        run: |
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" > .env
          echo "NEXT_PUBLIC_FIREBASE_KEY = ${{ secrets.NEXT_PUBLIC_FIREBASE_KEY }}" > .env
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}" > .env
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" > .env
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID = ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" > .env
          echo "NEXT_PUBLIC_FIREBASE_REALTIME_DB = ${{ secrets.NEXT_PUBLIC_FIREBASE_REALTIME_DB }}" > .env
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" > .env
          
      - run: npm install
      - run: npm run build
      
  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.FRONTEND_DEPLOY_KEY }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: --prod

# Path: .github/workflows/deploy.yml
# github action for deploying to vercel from github
